# 1. IMPORT LIBRARY

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# 2. LOAD DATASET

In [24]:
DATA_PATH = Path("../data/processed")

feature_A = pd.read_csv(DATA_PATH / "feature_A.csv")
feature_AB = pd.read_csv(DATA_PATH / "feature_AB.csv")

feature_A = feature_A.fillna(0)
feature_AB = feature_AB.fillna(0)

feature_A.head()
feature_AB.head()

,user_id,source_folder,followers_count,friends_count,statuses_count,listed_count,favourites_count,verified,protected,geo_enabled,...,label,tweet_count,avg_tweet_length,avg_hashtag_count,avg_url_count,avg_mention_count,avg_posting_interval,retweet_ratio,sync_hashtag_score,duplicate_content_score
0,1502026416,genuine_accounts,208,332,2177,1,265,0,0,1,...,human,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2492782375,genuine_accounts,330,485,2660,5,3972,0,0,1,...,human,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,293212315,genuine_accounts,166,177,1254,0,1185,0,0,0,...,human,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,191839658,genuine_accounts,2248,981,202968,101,60304,0,0,1,...,human,3220.0,67.91944,0.142768,0.337481,0.840435,534.917366,0.339658,1.419214,1.344946
4,3020965143,genuine_accounts,21,79,82,0,5,0,0,0,...,human,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

# 3. FEATURE A

split feature & label

In [25]:
X_A = feature_A.drop(columns=["user_id", "label", "source_folder"])

y_A = feature_A["label"]

Train Test Split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X_A,
    y_A,
    test_size=0.2,
    random_state=42,
    stratify=y_A
)

Standard Scaler

In [27]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

Training

In [28]:
lr_A = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_A.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

Prediction

In [29]:
y_pred = lr_A.predict(X_test)

Evaluation

In [30]:
acc_A = accuracy_score(y_test, y_pred)

pre_A = precision_score(
    y_test,
    y_pred,
    average="macro"
)

rec_A = recall_score(
    y_test,
    y_pred,
    average="macro"
)

f1_A = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print("Accuracy :", acc_A)
print("Precision:", pre_A)
print("Recall   :", rec_A)
print("F1 Score :", f1_A)

Accuracy : 0.9488517745302714
Precision: 0.9463448493001689
Recall   : 0.9118832148599615
F1 Score : 0.9275262698787781

Classification Report

In [31]:
print(classification_report(
    y_test,
    y_pred
))

              precision    recall  f1-score   support

         bot       0.95      0.98      0.97      2179
       human       0.94      0.84      0.89       695

    accuracy                           0.95      2874
   macro avg       0.95      0.91      0.93      2874
weighted avg       0.95      0.95      0.95      2874

# 4. FEATURE A+B

split feature

In [32]:
X_A = feature_A.drop(columns=["user_id", "label", "source_folder"], errors="ignore")
X_AB = feature_AB.drop(columns=["user_id", "label", "source_folder"], errors="ignore")
y_AB = feature_AB["label"]

Train Test Split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X_AB,
    y_AB,
    test_size=0.2,
    random_state=42,
    stratify=y_AB
)

Standard Scaler

In [34]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

Training

In [35]:
lr_AB = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_AB.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

Prediction

In [36]:
y_pred = lr_AB.predict(X_test)

Evaluation

In [37]:
acc_AB = accuracy_score(y_test, y_pred)

pre_AB = precision_score(
    y_test,
    y_pred,
    average="macro"
)

rec_AB = recall_score(
    y_test,
    y_pred,
    average="macro"
)

f1_AB = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print("Accuracy :", acc_AB)
print("Precision:", pre_AB)
print("Recall   :", rec_AB)
print("F1 Score :", f1_AB)

Accuracy : 0.9509394572025052
Precision: 0.9473891305704125
Recall   : 0.9166897230265352
F1 Score : 0.9307798147507591

Classification Report

In [38]:
print(classification_report(
    y_test,
    y_pred
))

              precision    recall  f1-score   support

         bot       0.95      0.98      0.97      2179
       human       0.94      0.85      0.89       695

    accuracy                           0.95      2874
   macro avg       0.95      0.92      0.93      2874
weighted avg       0.95      0.95      0.95      2874

# 5. FINAL RESULT

In [39]:
results = pd.DataFrame({
    "Feature": ["A", "A+B"],
    "Accuracy": [acc_A, acc_AB],
    "Precision": [pre_A, pre_AB],
    "Recall": [rec_A, rec_AB],
    "F1 Score": [f1_A, f1_AB]
})

results

  Feature  Accuracy  Precision    Recall  F1 Score
0       A  0.948852   0.946345  0.911883  0.927526
1     A+B  0.950939   0.947389  0.916690  0.930780

In [40]:
RESULT_PATH = Path("../results")
RESULT_PATH.mkdir(parents=True, exist_ok=True)
results.to_csv(RESULT_PATH / "logistic_regression_results.csv", index=False)